/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projprop;

/**
 *
 * @author hp_cust
 */
public class errorM extends javax.swing.JFrame {

    /**
     * Creates new form errorM
     */
    public errorM(String m) {
        initComponents();
        
        mBox.setText(m);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        close_ = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mBox = new javax.swing.JLabel();
        okbtn_ = new javax.swing.JLabel();
        closewrn_ = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        close_.setBackground(new java.awt.Color(255, 0, 0));
        close_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        close_.setForeground(new java.awt.Color(240, 240, 240));
        close_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_.setText("X");
        close_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        mBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        mBox.setForeground(new java.awt.Color(240, 240, 240));
        mBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        okbtn_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        okbtn_.setForeground(new java.awt.Color(240, 240, 240));
        okbtn_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        okbtn_.setText("OK");
        okbtn_.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        okbtn_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okbtn_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okbtn_MouseClicked(evt);
            }
        });

        closewrn_.setBackground(new java.awt.Color(255, 0, 0));
        closewrn_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closewrn_.setForeground(new java.awt.Color(240, 240, 240));
        closewrn_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closewrn_.setText("X");
        closewrn_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closewrn_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closewrn_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mBox, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(okbtn_, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closewrn_, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closewrn_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(mBox, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okbtn_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okbtn_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okbtn_MouseClicked
        // TODO add your handling code here:
        //projectProp p = new projectProp();
        //p.setVisible(true);
        dispose();
    }//GEN-LAST:event_okbtn_MouseClicked

    private void close_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_MouseClicked
        dispose();
    }//GEN-LAST:event_close_MouseClicked

    private void closewrn_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closewrn_MouseClicked
        dispose();
    }//GEN-LAST:event_closewrn_MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_;
    private javax.swing.JLabel closewrn_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mBox;
    private javax.swing.JLabel okbtn_;
    // End of variables declaration//GEN-END:variables
}
